---
name: 'Bug report'
about: 'Create a bug report'
---

## Bug report

### Current Behavior

<!-- If applicable, add screenshots/videos to help explain the problem. -->

### Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

### Reproducible example

[StackBlitz Template](https://stackblitz.com/edit/react-ts-z7abvy?file=App.tsx)

### Suggested solution

<!-- How could we solve this bug? What changes would need to made? -->

### Additional context

<!-- Add any other context about the problem here.  -->

### Your environment

<!-- Very important for us to help you debug. Please fill this out! -->

| Software         | Name(s) | Version |
| ---------------- | ------- | ------- |
| Custom Hook      |         |         |
| React            | n/a     |         |
| Browser          |         |         |
| Assistive tech   |         |         |
| Node             | n/a     |         |
| npm/yarn         |         |         |
| Operating System |         |         |